import Foundation

public struct RuntimeLinkInfo {
    public let libraryPaths: [String]
    public let libraries: [String]
    public let extraObjects: [String]

    public init(libraryPaths: [String], libraries: [String], extraObjects: [String]) {
        self.libraryPaths = libraryPaths
        self.libraries = libraries
        self.extraObjects = extraObjects
    }
}

public final class LLVMBackend {
    private let target: TargetTriple
    private let optLevel: OptimizationLevel
    private let debugInfo: Bool
    private let diagnostics: DiagnosticEngine

    public init(
        target: TargetTriple,
        optLevel: OptimizationLevel,
        debugInfo: Bool,
        diagnostics: DiagnosticEngine
    ) {
        self.target = target
        self.optLevel = optLevel
        self.debugInfo = debugInfo
        self.diagnostics = diagnostics
    }

    public func emitObject(
        module: KIRModule,
        runtime: RuntimeLinkInfo,
        outputObjectPath: String,
        interner: StringInterner
    ) throws {
        let source = renderCModule(module: module, interner: interner)
        let tempDir = FileManager.default.temporaryDirectory
        let sourceURL = tempDir.appendingPathComponent(UUID().uuidString + ".c")
        defer {
            try? FileManager.default.removeItem(at: sourceURL)
        }

        do {
            try source.write(to: sourceURL, atomically: true, encoding: .utf8)
            var args = ["-x", "c", "-std=c11", "-c", sourceURL.path, "-o", outputObjectPath]
            args.append(contentsOf: clangTargetArgs())
            _ = try CommandRunner.run(executable: "/usr/bin/clang", arguments: args)
        } catch let error as CommandRunnerError {
            reportBackendError(
                code: "KSWIFTK-BACKEND-0001",
                message: "clang failed while emitting object output: \(outputObjectPath)",
                error: error
            )
            throw error
        } catch {
            diagnostics.error(
                "KSWIFTK-BACKEND-0001",
                "Failed to emit object output: \(outputObjectPath)",
                range: nil
            )
            throw error
        }
    }

    public func emitLLVMIR(
        module: KIRModule,
        runtime: RuntimeLinkInfo,
        outputIRPath: String,
        interner: StringInterner
    ) throws {
        let source = renderCModule(module: module, interner: interner)
        let tempDir = FileManager.default.temporaryDirectory
        let sourceURL = tempDir.appendingPathComponent(UUID().uuidString + ".c")
        defer {
            try? FileManager.default.removeItem(at: sourceURL)
        }

        do {
            try source.write(to: sourceURL, atomically: true, encoding: .utf8)
            var args = ["-x", "c", "-std=c11", "-S", "-emit-llvm", sourceURL.path, "-o", outputIRPath]
            args.append(contentsOf: clangTargetArgs())
            _ = try CommandRunner.run(executable: "/usr/bin/clang", arguments: args)
        } catch let error as CommandRunnerError {
            reportBackendError(
                code: "KSWIFTK-BACKEND-0002",
                message: "clang failed while emitting LLVM IR output: \(outputIRPath)",
                error: error
            )
            throw error
        } catch {
            diagnostics.error(
                "KSWIFTK-BACKEND-0002",
                "Failed to emit LLVM IR output: \(outputIRPath)",
                range: nil
            )
            throw error
        }
    }

    public static func cFunctionSymbol(for function: KIRFunction, interner: StringInterner) -> String {
        let rawName = interner.resolve(function.name)
        let safeName = sanitizeForCSymbol(rawName)
        let suffix = max(0, function.symbol.rawValue)
        return "kk_fn_\(safeName)_\(suffix)"
    }

    private func targetTripleString() -> String {
        if let osVersion = target.osVersion, !osVersion.isEmpty {
            return "\(target.arch)-\(target.vendor)-\(target.os)\(osVersion)"
        }
        return "\(target.arch)-\(target.vendor)-\(target.os)"
    }

    private func renderCModule(module: KIRModule, interner: StringInterner) -> String {
        let functionSymbols: [SymbolID: String] = module.arena.declarations.reduce(into: [:]) { acc, decl in
            guard case .function(let function) = decl else {
                return
            }
            acc[function.symbol] = Self.cFunctionSymbol(for: function, interner: interner)
        }

        var lines: [String] = [
            "#include <stdint.h>",
            "#include <stddef.h>",
            "#include <stdlib.h>",
            "#include <stdio.h>",
            "#include <string.h>",
            "",
            "/* Generated by KSwiftK synthetic backend */",
            "typedef struct { int32_t len; uint8_t* bytes; } KKString;",
            "static void* kk_string_from_utf8(const uint8_t* ptr, int32_t len) {",
            "  if (len < 0) len = 0;",
            "  KKString* s = (KKString*)malloc(sizeof(KKString));",
            "  if (!s) return NULL;",
            "  s->len = len;",
            "  s->bytes = NULL;",
            "  if (len > 0) {",
            "    s->bytes = (uint8_t*)malloc((size_t)len);",
            "    if (!s->bytes) { free(s); return NULL; }",
            "    memcpy(s->bytes, ptr, (size_t)len);",
            "  }",
            "  return (void*)s;",
            "}",
            "static void* kk_string_concat(void* a, void* b) {",
            "  KKString* lhs = (KKString*)a;",
            "  KKString* rhs = (KKString*)b;",
            "  int32_t l = lhs ? lhs->len : 0;",
            "  int32_t r = rhs ? rhs->len : 0;",
            "  int32_t n = l + r;",
            "  KKString* out = (KKString*)malloc(sizeof(KKString));",
            "  if (!out) return NULL;",
            "  out->len = n;",
            "  out->bytes = NULL;",
            "  if (n > 0) {",
            "    out->bytes = (uint8_t*)malloc((size_t)n);",
            "    if (!out->bytes) { free(out); return NULL; }",
            "    if (lhs && lhs->bytes && l > 0) memcpy(out->bytes, lhs->bytes, (size_t)l);",
            "    if (rhs && rhs->bytes && r > 0) memcpy(out->bytes + l, rhs->bytes, (size_t)r);",
            "  }",
            "  return (void*)out;",
            "}",
            "static void kk_println_any(void* obj) {",
            "  if (!obj) { puts(\"null\"); return; }",
            "  KKString* s = (KKString*)obj;",
            "  if (s->bytes && s->len > 0) fwrite(s->bytes, 1, (size_t)s->len, stdout);",
            "  fputc('\\n', stdout);",
            "}",
            "static void* kk_coroutine_suspended(void) {",
            "  static int32_t token = 0;",
            "  return (void*)&token;",
            "}",
            ""
        ]

        for decl in module.arena.declarations {
            guard case .function(let function) = decl else {
                continue
            }
            lines.append(functionPrototype(function: function, interner: interner) + ";")
        }
        lines.append("")
        lines.append("int32_t kk_module_function_count(void) { return \(module.functionCount); }")
        lines.append("")

        for decl in module.arena.declarations {
            guard case .function(let function) = decl else {
                continue
            }
            lines.append(functionPrototype(function: function, interner: interner) + " {")
            lines.append(contentsOf: emitFunctionBody(function: function, interner: interner, arena: module.arena, functionSymbols: functionSymbols))
            lines.append("}")
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    private func functionPrototype(function: KIRFunction, interner: StringInterner) -> String {
        let symbol = Self.cFunctionSymbol(for: function, interner: interner)
        let params: String
        if function.params.isEmpty {
            params = "void"
        } else {
            params = function.params.enumerated().map { index, _ in
                "intptr_t p\(index)"
            }.joined(separator: ", ")
        }
        return "intptr_t \(symbol)(\(params))"
    }

    private func emitFunctionBody(
        function: KIRFunction,
        interner: StringInterner,
        arena: KIRArena,
        functionSymbols: [SymbolID: String]
    ) -> [String] {
        var lines: [String] = []
        var declared: Set<Int32> = []

        for instruction in function.body {
            switch instruction {
            case .nop:
                lines.append("  /* nop */")

            case .beginBlock, .endBlock:
                continue

            case .constValue(let result, let value):
                ensureDeclared(result, declared: &declared, lines: &lines)
                lines.append("  \(varName(result)) = \(valueExpr(value, interner: interner));")

            case .binary(let op, let lhs, let rhs, let result):
                ensureDeclared(result, declared: &declared, lines: &lines)
                ensureDeclared(lhs, declared: &declared, lines: &lines)
                ensureDeclared(rhs, declared: &declared, lines: &lines)
                let opText: String
                switch op {
                case .add:
                    opText = "+"
                case .subtract:
                    opText = "-"
                case .multiply:
                    opText = "*"
                case .divide:
                    opText = "/"
                case .equal:
                    opText = "=="
                }
                lines.append("  \(varName(result)) = (\(varName(lhs)) \(opText) \(varName(rhs)));")

            case .call(let symbol, let callee, let arguments, let result, _):
                let calleeName = interner.resolve(callee)
                let argVars = arguments.map { arg -> String in
                    ensureDeclared(arg, declared: &declared, lines: &lines)
                    return varName(arg)
                }

                if let result {
                    ensureDeclared(result, declared: &declared, lines: &lines)
                }

                if calleeName == "println" || calleeName == "kk_println_any" {
                    let value = argVars.first ?? "0"
                    lines.append("  kk_println_any((void*)\(value));")
                    if let result {
                        lines.append("  \(varName(result)) = 0;")
                    }
                    continue
                }

                if calleeName == "kk_op_add" || calleeName == "kk_op_sub" || calleeName == "kk_op_mul" || calleeName == "kk_op_div" || calleeName == "kk_op_eq" {
                    let lhs = argVars.count > 0 ? argVars[0] : "0"
                    let rhs = argVars.count > 1 ? argVars[1] : "0"
                    let expr: String
                    switch calleeName {
                    case "kk_op_add":
                        expr = "(\(lhs) + \(rhs))"
                    case "kk_op_sub":
                        expr = "(\(lhs) - \(rhs))"
                    case "kk_op_mul":
                        expr = "(\(lhs) * \(rhs))"
                    case "kk_op_div":
                        expr = "(\(lhs) / \(rhs))"
                    default:
                        expr = "(\(lhs) == \(rhs))"
                    }
                    if let result {
                        lines.append("  \(varName(result)) = \(expr);")
                    } else {
                        lines.append("  (void)\(expr);")
                    }
                    continue
                }

                if calleeName == "kk_when_select" {
                    let value = argVars.dropFirst().first ?? argVars.first ?? "0"
                    if let result {
                        lines.append("  \(varName(result)) = \(value);")
                    } else {
                        lines.append("  (void)\(value);")
                    }
                    continue
                }

                let target: String
                if let symbol, let resolved = functionSymbols[symbol] {
                    target = resolved
                } else {
                    target = calleeName.isEmpty ? "0" : calleeName
                }
                let callExpr = "\(target)(\(argVars.joined(separator: ", ")))"
                if let result {
                    lines.append("  \(varName(result)) = \(callExpr);")
                } else {
                    lines.append("  (void)\(callExpr);")
                }

            case .returnUnit:
                lines.append("  return 0;")

            case .returnValue(let value):
                ensureDeclared(value, declared: &declared, lines: &lines)
                lines.append("  return \(varName(value));")
            }
        }

        if lines.last?.hasPrefix("  return ") != true {
            lines.append("  return 0;")
        }
        return lines
    }

    private func ensureDeclared(_ id: KIRExprID, declared: inout Set<Int32>, lines: inout [String]) {
        guard declared.insert(id.rawValue).inserted else {
            return
        }
        lines.append("  intptr_t \(varName(id)) = 0;")
    }

    private func varName(_ id: KIRExprID) -> String {
        "r\(id.rawValue)"
    }

    private func valueExpr(_ value: KIRExprKind, interner: StringInterner) -> String {
        switch value {
        case .intLiteral(let number):
            return "\(number)"
        case .boolLiteral(let bool):
            return bool ? "1" : "0"
        case .stringLiteral(let interned):
            let text = interner.resolve(interned)
            let escaped = cStringLiteral(text)
            let byteCount = text.utf8.count
            return "(intptr_t)kk_string_from_utf8((const uint8_t*)\(escaped), \(byteCount))"
        case .symbolRef:
            return "0"
        case .temporary(let index):
            return "\(index)"
        case .unit:
            return "0"
        }
    }

    private func cStringLiteral(_ value: String) -> String {
        var escaped = "\""
        for scalar in value.unicodeScalars {
            switch scalar {
            case "\\":
                escaped += "\\\\"
            case "\"":
                escaped += "\\\""
            case "\n":
                escaped += "\\n"
            case "\r":
                escaped += "\\r"
            case "\t":
                escaped += "\\t"
            default:
                escaped += String(scalar)
            }
        }
        escaped += "\""
        return escaped
    }

    private static func sanitizeForCSymbol(_ text: String) -> String {
        if text.isEmpty {
            return "_"
        }
        var result = ""
        for (index, scalar) in text.unicodeScalars.enumerated() {
            let isAlphaNum = CharacterSet.alphanumerics.contains(scalar)
            if index == 0 {
                if CharacterSet.letters.contains(scalar) || scalar == "_" {
                    result.append(Character(scalar))
                } else if isAlphaNum {
                    result.append("_")
                    result.append(Character(scalar))
                } else {
                    result.append("_")
                }
            } else if isAlphaNum || scalar == "_" {
                result.append(Character(scalar))
            } else {
                result.append("_")
            }
        }
        if result.isEmpty {
            return "_"
        }
        return result
    }

    private func clangTargetArgs() -> [String] {
        var triple = "\(target.arch)-\(target.vendor)-\(target.os)"
        if let version = target.osVersion, !version.isEmpty {
            triple += version
        }
        return ["-target", triple]
    }

    private func reportBackendError(code: String, message: String, error: CommandRunnerError) {
        switch error {
        case .launchFailed(let reason):
            diagnostics.error(code, "\(message). \(reason)", range: nil)
        case .nonZeroExit(let result):
            let stderr = result.stderr.trimmingCharacters(in: .whitespacesAndNewlines)
            if stderr.isEmpty {
                diagnostics.error(code, "\(message). exit=\(result.exitCode)", range: nil)
            } else {
                diagnostics.error(code, "\(message). \(stderr)", range: nil)
            }
        }
    }
}
