import Foundation

public struct RuntimeLinkInfo {
    public let libraryPaths: [String]
    public let libraries: [String]
    public let extraObjects: [String]

    public init(libraryPaths: [String], libraries: [String], extraObjects: [String]) {
        self.libraryPaths = libraryPaths
        self.libraries = libraries
        self.extraObjects = extraObjects
    }
}

public final class LLVMBackend {
    private let target: TargetTriple
    private let optLevel: OptimizationLevel
    private let debugInfo: Bool
    private let diagnostics: DiagnosticEngine

    public init(
        target: TargetTriple,
        optLevel: OptimizationLevel,
        debugInfo: Bool,
        diagnostics: DiagnosticEngine
    ) {
        self.target = target
        self.optLevel = optLevel
        self.debugInfo = debugInfo
        self.diagnostics = diagnostics
    }

    public func emitObject(
        module: KIRModule,
        runtime: RuntimeLinkInfo,
        outputObjectPath: String,
        interner: StringInterner
    ) throws {
        let source = renderCModule(module: module, interner: interner)
        let tempDir = FileManager.default.temporaryDirectory
        let sourceURL = tempDir.appendingPathComponent(UUID().uuidString + ".c")
        defer {
            try? FileManager.default.removeItem(at: sourceURL)
        }

        do {
            try source.write(to: sourceURL, atomically: true, encoding: .utf8)
            var args = ["-x", "c", "-std=c11", "-c", sourceURL.path, "-o", outputObjectPath]
            args.append(contentsOf: clangTargetArgs())
            try CommandRunner.run(executable: "/usr/bin/clang", arguments: args)
        } catch let error as CommandRunnerError {
            reportBackendError(
                code: "KSWIFTK-BACKEND-0001",
                message: "clang failed while emitting object output: \(outputObjectPath)",
                error: error
            )
            throw error
        } catch {
            diagnostics.error(
                "KSWIFTK-BACKEND-0001",
                "Failed to emit object output: \(outputObjectPath)",
                range: nil
            )
            throw error
        }
    }

    public func emitLLVMIR(
        module: KIRModule,
        runtime: RuntimeLinkInfo,
        outputIRPath: String,
        interner: StringInterner
    ) throws {
        let source = renderCModule(module: module, interner: interner)
        let tempDir = FileManager.default.temporaryDirectory
        let sourceURL = tempDir.appendingPathComponent(UUID().uuidString + ".c")
        defer {
            try? FileManager.default.removeItem(at: sourceURL)
        }

        do {
            try source.write(to: sourceURL, atomically: true, encoding: .utf8)
            var args = ["-x", "c", "-std=c11", "-S", "-emit-llvm", sourceURL.path, "-o", outputIRPath]
            args.append(contentsOf: clangTargetArgs())
            try CommandRunner.run(executable: "/usr/bin/clang", arguments: args)
        } catch let error as CommandRunnerError {
            reportBackendError(
                code: "KSWIFTK-BACKEND-0002",
                message: "clang failed while emitting LLVM IR output: \(outputIRPath)",
                error: error
            )
            throw error
        } catch {
            diagnostics.error(
                "KSWIFTK-BACKEND-0002",
                "Failed to emit LLVM IR output: \(outputIRPath)",
                range: nil
            )
            throw error
        }
    }

    public static func cFunctionSymbol(for function: KIRFunction, interner: StringInterner) -> String {
        let rawName = interner.resolve(function.name)
        let safeName = sanitizeForCSymbol(rawName)
        let suffix = max(0, function.symbol.rawValue)
        return "kk_fn_\(safeName)_\(suffix)"
    }

    private func targetTripleString() -> String {
        if let osVersion = target.osVersion, !osVersion.isEmpty {
            return "\(target.arch)-\(target.vendor)-\(target.os)\(osVersion)"
        }
        return "\(target.arch)-\(target.vendor)-\(target.os)"
    }

    private func renderCModule(module: KIRModule, interner: StringInterner) -> String {
        var lines: [String] = [
            "#include <stdint.h>",
            "",
            "/* Generated by KSwiftK synthetic backend */",
            "int32_t kk_module_function_count(void) {",
            "  return \(module.functionCount);",
            "}",
            ""
        ]

        for decl in module.arena.declarations {
            guard case .function(let function) = decl else {
                continue
            }
            let symbol = Self.cFunctionSymbol(for: function, interner: interner)
            lines.append("int32_t \(symbol)(void) {")
            lines.append("  (void)\(module.symbolCount);")
            lines.append("  return 0;")
            lines.append("}")
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    private static func sanitizeForCSymbol(_ text: String) -> String {
        if text.isEmpty {
            return "_"
        }
        var result = ""
        for (index, scalar) in text.unicodeScalars.enumerated() {
            let isAlphaNum = CharacterSet.alphanumerics.contains(scalar)
            if index == 0 {
                if CharacterSet.letters.contains(scalar) || scalar == "_" {
                    result.append(Character(scalar))
                } else if isAlphaNum {
                    result.append("_")
                    result.append(Character(scalar))
                } else {
                    result.append("_")
                }
            } else if isAlphaNum || scalar == "_" {
                result.append(Character(scalar))
            } else {
                result.append("_")
            }
        }
        if result.isEmpty {
            return "_"
        }
        return result
    }

    private func clangTargetArgs() -> [String] {
        var triple = "\(target.arch)-\(target.vendor)-\(target.os)"
        if let version = target.osVersion, !version.isEmpty {
            triple += version
        }
        return ["-target", triple]
    }

    private func reportBackendError(code: String, message: String, error: CommandRunnerError) {
        switch error {
        case .launchFailed(let reason):
            diagnostics.error(code, "\(message). \(reason)", range: nil)
        case .nonZeroExit(let result):
            let stderr = result.stderr.trimmingCharacters(in: .whitespacesAndNewlines)
            if stderr.isEmpty {
                diagnostics.error(code, "\(message). exit=\(result.exitCode)", range: nil)
            } else {
                diagnostics.error(code, "\(message). \(stderr)", range: nil)
            }
        }
    }
}
