import Foundation

extension LLVMBackend {
    /// Minimal C declarations sufficient for compiling user code when the full
    /// runtime preamble has already been compiled into a cached stub object.
    /// Includes type definitions, macros, and extern declarations for all
    /// runtime functions that user code may reference.
    ///
    /// Stored as a static constant to avoid re-creating the array on every
    /// compilation (P5-64).
    static let fixedExternDeclarations: [String] = [
            "#define _DEFAULT_SOURCE",
            "#include <stdint.h>",
            "#include <stddef.h>",
            "#include <stdlib.h>",
            "#include <stdio.h>",
            "#include <string.h>",
            "#include <unistd.h>",
            "#include <math.h>",
            "#define KK_NULL_SENTINEL ((intptr_t)INTPTR_MIN)",
            "",
            "/* Type definitions shared with runtime stub */",
            "typedef struct { int32_t len; uint8_t* bytes; } KKString;",
            "typedef struct { uint32_t rootCount; const int32_t* rootOffsets; } KKFrameMapDescriptor;",
            "typedef intptr_t (*KKVTableEntry)();",
            "typedef intptr_t (*KKSuspendEntryFn)(intptr_t continuation, intptr_t* outThrown);",
            "",
            "/* Extern declarations for runtime functions in cached stub */",
            "extern void kk_register_frame_map(uint32_t functionID, const void* mapPtr);",
            "extern void kk_push_frame(uint32_t functionID, void* frameBase);",
            "extern void kk_pop_frame(void);",
            "extern void kk_register_global_root(void** slot);",
            "extern void kk_unregister_global_root(void** slot);",
            "extern void kk_register_coroutine_root(void* value);",
            "extern void kk_unregister_coroutine_root(void* value);",
            "extern void* kk_string_from_utf8(const uint8_t* ptr, int32_t len);",
            "extern void* kk_any_to_string(intptr_t value, int32_t tag);",
            "extern void* kk_string_concat(void* a, void* b);",
            "extern intptr_t kk_string_compareTo(void* a, void* b);",
            "extern intptr_t kk_array_new(intptr_t length);",
            "extern intptr_t kk_array_get(intptr_t arrayRaw, intptr_t index, intptr_t* outThrown);",
            "extern intptr_t kk_array_set(intptr_t arrayRaw, intptr_t index, intptr_t value, intptr_t* outThrown);",
            "extern intptr_t kk_vararg_spread_concat(intptr_t pairsArrayRaw, intptr_t pairCount);",
            "extern intptr_t kk_box_int(intptr_t value);",
            "extern intptr_t kk_box_bool(intptr_t value);",
            "extern intptr_t kk_unbox_int(intptr_t obj);",
            "extern intptr_t kk_unbox_bool(intptr_t obj);",
            "extern intptr_t kk_box_long(intptr_t value);",
            "extern intptr_t kk_unbox_long(intptr_t obj);",
            "extern intptr_t kk_float_to_bits(float f);",
            "extern float kk_bits_to_float(intptr_t v);",
            "extern intptr_t kk_double_to_bits(double d);",
            "extern double kk_bits_to_double(intptr_t v);",
            "extern intptr_t kk_box_float(intptr_t value);",
            "extern intptr_t kk_unbox_float(intptr_t obj);",
            "extern intptr_t kk_box_double(intptr_t value);",
            "extern intptr_t kk_unbox_double(intptr_t obj);",
            "extern intptr_t kk_box_char(intptr_t value);",
            "extern intptr_t kk_unbox_char(intptr_t obj);",
            "extern intptr_t kk_int_to_float_bits(intptr_t v);",
            "extern intptr_t kk_int_to_double_bits(intptr_t v);",
            "extern intptr_t kk_float_to_double_bits(intptr_t v);",
            "extern void kk_println_long(intptr_t v);",
            "extern void kk_println_float(intptr_t v);",
            "extern void kk_println_double(intptr_t v);",
            "extern void kk_println_char(intptr_t v);",
            "extern void kk_println_any(void* obj);",
            "extern intptr_t kk_coroutine_suspended(void);",
            "extern intptr_t kk_coroutine_continuation_new(intptr_t functionId);",
            "extern intptr_t kk_coroutine_state_enter(intptr_t continuation, intptr_t functionId);",
            "extern intptr_t kk_coroutine_state_set_label(intptr_t continuation, intptr_t label);",
            "extern intptr_t kk_coroutine_state_exit(intptr_t continuation, intptr_t value);",
            "extern intptr_t kk_coroutine_state_set_spill(intptr_t continuation, intptr_t slot, intptr_t value);",
            "extern intptr_t kk_coroutine_state_get_spill(intptr_t continuation, intptr_t slot);",
            "extern intptr_t kk_coroutine_state_set_completion(intptr_t continuation, intptr_t value);",
            "extern intptr_t kk_coroutine_state_get_completion(intptr_t continuation);",
            "extern intptr_t kk_kxmini_delay(intptr_t milliseconds, intptr_t continuation);",
            "extern intptr_t delay(intptr_t milliseconds, intptr_t* outThrown);",
            "extern intptr_t kk_kxmini_run_loop(KKSuspendEntryFn entry, intptr_t functionId);",
            "extern intptr_t kk_kxmini_run_blocking(intptr_t entryRaw, intptr_t functionId);",
            "extern intptr_t kk_kxmini_launch(intptr_t entryRaw, intptr_t functionId);",
            "extern intptr_t kk_kxmini_async(intptr_t entryRaw, intptr_t functionId);",
            "extern intptr_t kk_kxmini_async_await(intptr_t handle);",
            "extern intptr_t kk_flow_create(intptr_t emitterFnPtr, intptr_t continuation);",
            "extern intptr_t kk_flow_emit(intptr_t flowHandle, intptr_t value, intptr_t continuation);",
            "extern intptr_t kk_flow_collect(intptr_t flowHandle, intptr_t collectorFnPtr, intptr_t continuation);",
            "extern intptr_t kk_dispatcher_default(void);",
            "extern intptr_t kk_dispatcher_io(void);",
            "extern intptr_t kk_dispatcher_main(void);",
            "extern intptr_t kk_with_context(intptr_t dispatcher, intptr_t blockFnPtr, intptr_t continuation);",
            "extern intptr_t kk_channel_create(intptr_t capacity);",
            "extern intptr_t kk_channel_send(intptr_t handle, intptr_t value, intptr_t continuation);",
            "extern intptr_t kk_channel_receive(intptr_t handle, intptr_t continuation);",
            "extern intptr_t kk_channel_close(intptr_t handle);",
            "extern intptr_t kk_await_all(intptr_t handlesArray, intptr_t count);",
            "extern KKVTableEntry kk_vtable_lookup(intptr_t receiver, intptr_t slot);",
            "extern KKVTableEntry kk_itable_lookup(intptr_t receiver, intptr_t ifaceSlot, intptr_t methodSlot);",
            "/* Range/progression runtime (P5-68) */",
            "typedef struct { intptr_t first; intptr_t last; intptr_t step; } KKRange;",
            "typedef struct { intptr_t current; intptr_t last; intptr_t step; } KKRangeIterator;",
            "extern intptr_t kk_op_rangeTo(intptr_t a, intptr_t b);",
            "extern intptr_t kk_op_rangeUntil(intptr_t a, intptr_t b);",
            "extern intptr_t kk_op_downTo(intptr_t a, intptr_t b);",
            "extern intptr_t kk_op_step(intptr_t rangeRaw, intptr_t stepVal);",
            "extern intptr_t kk_range_iterator(intptr_t rangeRaw);",
            "extern intptr_t kk_range_hasNext(intptr_t iterRaw);",
            "extern intptr_t kk_range_next(intptr_t iterRaw);",
            ""
    ]

    func cRuntimeExternDeclarations() -> [String] {
        Self.fixedExternDeclarations
    }

    /// Full C runtime preamble including all function implementations.
    /// Stored as a static constant to avoid re-creating ~620 lines of strings
    /// on every compilation (P5-64).
    static let fixedRuntimePreamble: [String] = [
            "#define _DEFAULT_SOURCE",
            "#include <stdint.h>",
            "#include <stddef.h>",
            "#include <stdlib.h>",
            "#include <stdio.h>",
            "#include <string.h>",
            "#include <unistd.h>",
            "#include <math.h>",
            "#define KK_NULL_SENTINEL ((intptr_t)INTPTR_MIN)",
            "",
            "/* Generated by KSwiftK synthetic backend */",
            "typedef struct { int32_t len; uint8_t* bytes; } KKString;",
            "typedef struct { uint32_t rootCount; const int32_t* rootOffsets; } KKFrameMapDescriptor;",
            "/* --- Runtime GC data structures --- */",
            "typedef struct { uint32_t functionID; uint32_t rootCount; int32_t* rootOffsets; } KKFrameMapEntry;",
            "static KKFrameMapEntry* kk_rt_fmaps = NULL;",
            "static uint32_t kk_rt_fmap_cnt = 0;",
            "static uint32_t kk_rt_fmap_cap = 0;",
            "typedef struct { uint32_t functionID; void* frameBase; } KKActiveFrame;",
            "static KKActiveFrame* kk_rt_frames = NULL;",
            "static uint32_t kk_rt_frame_cnt = 0;",
            "static uint32_t kk_rt_frame_cap = 0;",
            "static void*** kk_rt_groots = NULL;",
            "static uint32_t kk_rt_groot_cnt = 0;",
            "static uint32_t kk_rt_groot_cap = 0;",
            "static void** kk_rt_croots = NULL;",
            "static uint32_t kk_rt_croot_cnt = 0;",
            "static uint32_t kk_rt_croot_cap = 0;",
            "",
            "__attribute__((weak)) void kk_register_frame_map(uint32_t functionID, const void* mapPtr) {",
            "  if (!mapPtr) {",
            "    for (uint32_t i = 0; i < kk_rt_fmap_cnt; i++) {",
            "      if (kk_rt_fmaps[i].functionID == functionID) {",
            "        free(kk_rt_fmaps[i].rootOffsets);",
            "        kk_rt_fmaps[i] = kk_rt_fmaps[--kk_rt_fmap_cnt];",
            "        return;",
            "      }",
            "    }",
            "    return;",
            "  }",
            "  const KKFrameMapDescriptor* desc = (const KKFrameMapDescriptor*)mapPtr;",
            "  uint32_t cnt = desc->rootCount;",
            "  int32_t* offs = NULL;",
            "  if (cnt > 0 && desc->rootOffsets) {",
            "    offs = (int32_t*)malloc(cnt * sizeof(int32_t));",
            "    if (!offs) { cnt = 0; } else memcpy(offs, desc->rootOffsets, cnt * sizeof(int32_t));",
            "  } else { cnt = 0; }",
            "  for (uint32_t i = 0; i < kk_rt_fmap_cnt; i++) {",
            "    if (kk_rt_fmaps[i].functionID == functionID) {",
            "      free(kk_rt_fmaps[i].rootOffsets);",
            "      kk_rt_fmaps[i].rootCount = cnt;",
            "      kk_rt_fmaps[i].rootOffsets = offs;",
            "      return;",
            "    }",
            "  }",
            "  if (kk_rt_fmap_cnt >= kk_rt_fmap_cap) {",
            "    uint32_t nc = kk_rt_fmap_cap == 0 ? 16 : kk_rt_fmap_cap * 2;",
            "    KKFrameMapEntry* p = (KKFrameMapEntry*)realloc(kk_rt_fmaps, nc * sizeof(KKFrameMapEntry));",
            "    if (!p) { free(offs); return; }",
            "    kk_rt_fmaps = p; kk_rt_fmap_cap = nc;",
            "  }",
            "  kk_rt_fmaps[kk_rt_fmap_cnt].functionID = functionID;",
            "  kk_rt_fmaps[kk_rt_fmap_cnt].rootCount = cnt;",
            "  kk_rt_fmaps[kk_rt_fmap_cnt].rootOffsets = offs;",
            "  kk_rt_fmap_cnt++;",
            "}",
            "__attribute__((weak)) void kk_push_frame(uint32_t functionID, void* frameBase) {",
            "  if (kk_rt_frame_cnt >= kk_rt_frame_cap) {",
            "    uint32_t nc = kk_rt_frame_cap == 0 ? 32 : kk_rt_frame_cap * 2;",
            "    KKActiveFrame* p = (KKActiveFrame*)realloc(kk_rt_frames, nc * sizeof(KKActiveFrame));",
            "    if (!p) return;",
            "    kk_rt_frames = p; kk_rt_frame_cap = nc;",
            "  }",
            "  kk_rt_frames[kk_rt_frame_cnt].functionID = functionID;",
            "  kk_rt_frames[kk_rt_frame_cnt].frameBase = frameBase;",
            "  kk_rt_frame_cnt++;",
            "}",
            "__attribute__((weak)) void kk_pop_frame(void) {",
            "  if (kk_rt_frame_cnt > 0) kk_rt_frame_cnt--;",
            "}",
            "__attribute__((weak)) void kk_register_global_root(void** slot) {",
            "  if (!slot) return;",
            "  for (uint32_t i = 0; i < kk_rt_groot_cnt; i++) {",
            "    if (kk_rt_groots[i] == slot) return;",
            "  }",
            "  if (kk_rt_groot_cnt >= kk_rt_groot_cap) {",
            "    uint32_t nc = kk_rt_groot_cap == 0 ? 16 : kk_rt_groot_cap * 2;",
            "    void*** p = (void***)realloc(kk_rt_groots, nc * sizeof(void**));",
            "    if (!p) return;",
            "    kk_rt_groots = p; kk_rt_groot_cap = nc;",
            "  }",
            "  kk_rt_groots[kk_rt_groot_cnt++] = slot;",
            "}",
            "__attribute__((weak)) void kk_unregister_global_root(void** slot) {",
            "  if (!slot) return;",
            "  for (uint32_t i = 0; i < kk_rt_groot_cnt; i++) {",
            "    if (kk_rt_groots[i] == slot) {",
            "      kk_rt_groots[i] = kk_rt_groots[--kk_rt_groot_cnt];",
            "      return;",
            "    }",
            "  }",
            "}",
            "__attribute__((weak)) void kk_register_coroutine_root(void* value) {",
            "  if (!value) return;",
            "  for (uint32_t i = 0; i < kk_rt_croot_cnt; i++) {",
            "    if (kk_rt_croots[i] == value) return;",
            "  }",
            "  if (kk_rt_croot_cnt >= kk_rt_croot_cap) {",
            "    uint32_t nc = kk_rt_croot_cap == 0 ? 16 : kk_rt_croot_cap * 2;",
            "    void** p = (void**)realloc(kk_rt_croots, nc * sizeof(void*));",
            "    if (!p) return;",
            "    kk_rt_croots = p; kk_rt_croot_cap = nc;",
            "  }",
            "  kk_rt_croots[kk_rt_croot_cnt++] = value;",
            "}",
            "__attribute__((weak)) void kk_unregister_coroutine_root(void* value) {",
            "  if (!value) return;",
            "  for (uint32_t i = 0; i < kk_rt_croot_cnt; i++) {",
            "    if (kk_rt_croots[i] == value) {",
            "      kk_rt_croots[i] = kk_rt_croots[--kk_rt_croot_cnt];",
            "      return;",
            "    }",
            "  }",
            "}",
            "",
            "__attribute__((weak)) void* kk_string_from_utf8(const uint8_t* ptr, int32_t len) {",
            "  if (len < 0) len = 0;",
            "  KKString* s = (KKString*)malloc(sizeof(KKString));",
            "  if (!s) return NULL;",
            "  s->len = len;",
            "  s->bytes = NULL;",
            "  if (len > 0) {",
            "    s->bytes = (uint8_t*)malloc((size_t)len);",
            "    if (!s->bytes) { free(s); return NULL; }",
            "    memcpy(s->bytes, ptr, (size_t)len);",
            "  }",
            "  return (void*)s;",
            "}",
            "__attribute__((weak)) void* kk_any_to_string(intptr_t value, int32_t tag) {",
            "  if (value == KK_NULL_SENTINEL) return kk_string_from_utf8((const uint8_t*)\"null\", 4);",
            "  char buf[64];",
            "  int len = 0;",
            "  switch (tag) {",
            #"    case 1: len = snprintf(buf, sizeof(buf), "%lld", (long long)value); break;"#,
            #"    case 2: len = snprintf(buf, sizeof(buf), "%s", (value ? "true" : "false")); break;"#,
            "    case 3: return (void*)value;",
            #"    default: len = snprintf(buf, sizeof(buf), "%lld", (long long)value); break;"#,
            "  }",
            "  if (len < 0) len = 0;",
            "  if (len >= (int)sizeof(buf)) len = (int)sizeof(buf) - 1;",
            "  buf[len] = '\\0';",
            "  return kk_string_from_utf8((const uint8_t*)buf, (int32_t)len);",
            "}",
            "__attribute__((weak)) void* kk_string_concat(void* a, void* b) {",
            "  if ((intptr_t)a == KK_NULL_SENTINEL) a = NULL;",
            "  if ((intptr_t)b == KK_NULL_SENTINEL) b = NULL;",
            "  KKString* lhs = (KKString*)a;",
            "  KKString* rhs = (KKString*)b;",
            "  int32_t l = lhs ? lhs->len : 0;",
            "  int32_t r = rhs ? rhs->len : 0;",
            "  int32_t n = l + r;",
            "  KKString* out = (KKString*)malloc(sizeof(KKString));",
            "  if (!out) return NULL;",
            "  out->len = n;",
            "  out->bytes = NULL;",
            "  if (n > 0) {",
            "    out->bytes = (uint8_t*)malloc((size_t)n);",
            "    if (!out->bytes) { free(out); return NULL; }",
            "    if (lhs && lhs->bytes && l > 0) memcpy(out->bytes, lhs->bytes, (size_t)l);",
            "    if (rhs && rhs->bytes && r > 0) memcpy(out->bytes + l, rhs->bytes, (size_t)r);",
            "  }",
            "  return (void*)out;",
            "}",
            "__attribute__((weak)) intptr_t kk_string_compareTo(void* a, void* b) {",
            "  if ((intptr_t)a == KK_NULL_SENTINEL) a = NULL;",
            "  if ((intptr_t)b == KK_NULL_SENTINEL) b = NULL;",
            "  KKString* lhs = (KKString*)a;",
            "  KKString* rhs = (KKString*)b;",
            "  int32_t l = lhs ? lhs->len : 0;",
            "  int32_t r = rhs ? rhs->len : 0;",
            "  int32_t minLen = l < r ? l : r;",
            "  if (minLen > 0 && lhs->bytes && rhs->bytes) {",
            "    int c = memcmp(lhs->bytes, rhs->bytes, (size_t)minLen);",
            "    if (c != 0) return (intptr_t)(c < 0 ? -1 : 1);",
            "  }",
            "  if (l < r) return (intptr_t)-1;",
            "  if (l > r) return (intptr_t)1;",
            "  return (intptr_t)0;",
            "}",
            "typedef struct {",
            "  intptr_t length;",
            "  intptr_t* elements;",
            "} KKArray;",
            "__attribute__((weak)) intptr_t kk_array_new(intptr_t length) {",
            "  if (length < 0) length = 0;",
            "  KKArray* array = (KKArray*)malloc(sizeof(KKArray));",
            "  if (!array) return 0;",
            "  array->length = length;",
            "  array->elements = NULL;",
            "  if (length > 0) {",
            "    array->elements = (intptr_t*)calloc((size_t)length, sizeof(intptr_t));",
            "    if (!array->elements) { free(array); return 0; }",
            "  }",
            "  return (intptr_t)array;",
            "}",
            "__attribute__((weak)) intptr_t kk_array_get(intptr_t arrayRaw, intptr_t index, intptr_t* outThrown) {",
            "  if (outThrown) { *outThrown = 0; }",
            "  KKArray* array = (KKArray*)(void*)arrayRaw;",
            "  if (!array || index < 0 || index >= array->length) {",
            "    if (outThrown) { *outThrown = 1; }",
            "    return 0;",
            "  }",
            "  return array->elements[index];",
            "}",
            "__attribute__((weak)) intptr_t kk_array_set(intptr_t arrayRaw, intptr_t index, intptr_t value, intptr_t* outThrown) {",
            "  if (outThrown) { *outThrown = 0; }",
            "  KKArray* array = (KKArray*)(void*)arrayRaw;",
            "  if (!array || index < 0 || index >= array->length) {",
            "    if (outThrown) { *outThrown = 1; }",
            "    return 0;",
            "  }",
            "  array->elements[index] = value;",
            "  return value;",
            "}",
            "__attribute__((weak)) intptr_t kk_vararg_spread_concat(intptr_t pairsArrayRaw, intptr_t pairCount) {",
            "  KKArray* pairs = (KKArray*)(void*)pairsArrayRaw;",
            "  if (!pairs || pairCount <= 0) return kk_array_new(0);",
            "  if (pairs->length < pairCount * 2) return kk_array_new(0);",
            "  intptr_t totalLen = 0;",
            "  for (intptr_t i = 0; i < pairCount; i++) {",
            "    intptr_t marker = pairs->elements[i * 2];",
            "    intptr_t value = pairs->elements[i * 2 + 1];",
            "    if (marker == -1) {",
            "      KKArray* src = (KKArray*)(void*)value;",
            "      if (src) totalLen += src->length;",
            "    } else { totalLen++; }",
            "  }",
            "  intptr_t arr = kk_array_new(totalLen);",
            "  KKArray* out = (KKArray*)(void*)arr;",
            "  intptr_t pos = 0;",
            "  for (intptr_t i = 0; i < pairCount; i++) {",
            "    intptr_t marker = pairs->elements[i * 2];",
            "    intptr_t value = pairs->elements[i * 2 + 1];",
            "    if (marker == -1) {",
            "      KKArray* src = (KKArray*)(void*)value;",
            "      if (src) { for (intptr_t j = 0; j < src->length; j++) out->elements[pos++] = src->elements[j]; }",
            "    } else { out->elements[pos++] = value; }",
            "  }",
            "  return arr;",
            "}",
            "typedef struct { intptr_t tag; intptr_t value; } KKBoxedValue;",
            "#define KK_BOX_TAG_INT    0x4B424F49",
            "#define KK_BOX_TAG_BOOL   0x4B424F42",
            "#define KK_BOX_TAG_LONG   0x4B424F4C",
            "#define KK_BOX_TAG_FLOAT  0x4B424F46",
            "#define KK_BOX_TAG_DOUBLE 0x4B424F44",
            "#define KK_BOX_TAG_CHAR   0x4B424F43",
            "__attribute__((weak)) intptr_t kk_box_int(intptr_t value) {",
            "  if (value == KK_NULL_SENTINEL) return value;",
            "  KKBoxedValue* box = (KKBoxedValue*)malloc(sizeof(KKBoxedValue));",
            "  if (!box) return value;",
            "  box->tag = KK_BOX_TAG_INT;",
            "  box->value = value;",
            "  return (intptr_t)box;",
            "}",
            "__attribute__((weak)) intptr_t kk_box_bool(intptr_t value) {",
            "  if (value == KK_NULL_SENTINEL) return value;",
            "  KKBoxedValue* box = (KKBoxedValue*)malloc(sizeof(KKBoxedValue));",
            "  if (!box) return value;",
            "  box->tag = KK_BOX_TAG_BOOL;",
            "  box->value = value != 0 ? 1 : 0;",
            "  return (intptr_t)box;",
            "}",
            "__attribute__((weak)) intptr_t kk_unbox_int(intptr_t obj) {",
            "  if (obj == KK_NULL_SENTINEL) return 0;",
            "  if (obj > -(intptr_t)0x100000000LL && obj < (intptr_t)0x100000000LL) return obj;",
            "  KKBoxedValue* box = (KKBoxedValue*)(void*)obj;",
            "  if (box && box->tag == KK_BOX_TAG_INT) return box->value;",
            "  return obj;",
            "}",
            "__attribute__((weak)) intptr_t kk_unbox_bool(intptr_t obj) {",
            "  if (obj == KK_NULL_SENTINEL) return 0;",
            "  if (obj > -(intptr_t)0x100000000LL && obj < (intptr_t)0x100000000LL) return obj != 0 ? 1 : 0;",
            "  KKBoxedValue* box = (KKBoxedValue*)(void*)obj;",
            "  if (box && box->tag == KK_BOX_TAG_BOOL) return box->value;",
            "  return obj != 0 ? 1 : 0;",
            "}",
            "__attribute__((weak)) intptr_t kk_box_long(intptr_t value) {",
            "  if (value == KK_NULL_SENTINEL) return value;",
            "  KKBoxedValue* box = (KKBoxedValue*)malloc(sizeof(KKBoxedValue));",
            "  if (!box) return value;",
            "  box->tag = KK_BOX_TAG_LONG;",
            "  box->value = value;",
            "  return (intptr_t)box;",
            "}",
            "__attribute__((weak)) intptr_t kk_unbox_long(intptr_t obj) {",
            "  if (obj == KK_NULL_SENTINEL) return 0;",
            "  KKBoxedValue* box = (KKBoxedValue*)(void*)obj;",
            "  if (box && box->tag == KK_BOX_TAG_LONG) return box->value;",
            "  return obj;",
            "}",
            "__attribute__((weak)) intptr_t kk_float_to_bits(float f) {",
            "  uint32_t bits; memcpy(&bits, &f, sizeof(float)); return (intptr_t)bits;",
            "}",
            "__attribute__((weak)) float kk_bits_to_float(intptr_t v) {",
            "  uint32_t bits = (uint32_t)v; float f; memcpy(&f, &bits, sizeof(float)); return f;",
            "}",
            "__attribute__((weak)) intptr_t kk_double_to_bits(double d) {",
            "  intptr_t bits; memcpy(&bits, &d, sizeof(double)); return bits;",
            "}",
            "__attribute__((weak)) double kk_bits_to_double(intptr_t v) {",
            "  double d; memcpy(&d, &v, sizeof(double)); return d;",
            "}",
            "__attribute__((weak)) intptr_t kk_box_float(intptr_t value) {",
            "  if (value == KK_NULL_SENTINEL) return value;",
            "  KKBoxedValue* box = (KKBoxedValue*)malloc(sizeof(KKBoxedValue));",
            "  if (!box) return value;",
            "  box->tag = KK_BOX_TAG_FLOAT;",
            "  box->value = value;",
            "  return (intptr_t)box;",
            "}",
            "__attribute__((weak)) intptr_t kk_unbox_float(intptr_t obj) {",
            "  if (obj == KK_NULL_SENTINEL) return 0;",
            "  KKBoxedValue* box = (KKBoxedValue*)(void*)obj;",
            "  if (box && box->tag == KK_BOX_TAG_FLOAT) return box->value;",
            "  return obj;",
            "}",
            "__attribute__((weak)) intptr_t kk_box_double(intptr_t value) {",
            "  if (value == KK_NULL_SENTINEL) return value;",
            "  KKBoxedValue* box = (KKBoxedValue*)malloc(sizeof(KKBoxedValue));",
            "  if (!box) return value;",
            "  box->tag = KK_BOX_TAG_DOUBLE;",
            "  box->value = value;",
            "  return (intptr_t)box;",
            "}",
            "__attribute__((weak)) intptr_t kk_unbox_double(intptr_t obj) {",
            "  if (obj == KK_NULL_SENTINEL) return 0;",
            "  KKBoxedValue* box = (KKBoxedValue*)(void*)obj;",
            "  if (box && box->tag == KK_BOX_TAG_DOUBLE) return box->value;",
            "  return obj;",
            "}",
            "__attribute__((weak)) intptr_t kk_box_char(intptr_t value) {",
            "  if (value == KK_NULL_SENTINEL) return value;",
            "  KKBoxedValue* box = (KKBoxedValue*)malloc(sizeof(KKBoxedValue));",
            "  if (!box) return value;",
            "  box->tag = KK_BOX_TAG_CHAR;",
            "  box->value = value;",
            "  return (intptr_t)box;",
            "}",
            "__attribute__((weak)) intptr_t kk_unbox_char(intptr_t obj) {",
            "  if (obj == KK_NULL_SENTINEL) return 0;",
            "  KKBoxedValue* box = (KKBoxedValue*)(void*)obj;",
            "  if (box && box->tag == KK_BOX_TAG_CHAR) return box->value;",
            "  return obj;",
            "}",
            "__attribute__((weak)) intptr_t kk_int_to_float_bits(intptr_t v) {",
            "  return kk_float_to_bits((float)v);",
            "}",
            "__attribute__((weak)) intptr_t kk_int_to_double_bits(intptr_t v) {",
            "  return kk_double_to_bits((double)v);",
            "}",
            "__attribute__((weak)) intptr_t kk_float_to_double_bits(intptr_t v) {",
            "  return kk_double_to_bits((double)kk_bits_to_float(v));",
            "}",
            "__attribute__((weak)) void kk_println_long(intptr_t v) {",
            "  printf(\"%ld\\n\", (long)v);",
            "}",
            "__attribute__((weak)) void kk_println_float(intptr_t v) {",
            "  float f = kk_bits_to_float(v);",
            "  if (f >= -2e9f && f <= 2e9f && f == (float)(int)f) { printf(\"%.1f\\n\", (double)f); }",
            "  else { printf(\"%g\\n\", (double)f); }",
            "}",
            "__attribute__((weak)) void kk_println_double(intptr_t v) {",
            "  double d = kk_bits_to_double(v);",
            "  if (d >= -1e15 && d <= 1e15 && d == (double)(long long)d) { printf(\"%.1f\\n\", d); }",
            "  else { printf(\"%g\\n\", d); }",
            "}",
            "__attribute__((weak)) void kk_println_char(intptr_t v) {",
            "  uint32_t cp = (uint32_t)v;",
            "  if (cp < 0x80) { putchar((int)cp); }",
            "  else if (cp < 0x800) { putchar((int)(0xC0 | (cp >> 6))); putchar((int)(0x80 | (cp & 0x3F))); }",
            "  else if (cp < 0x10000) { putchar((int)(0xE0 | (cp >> 12))); putchar((int)(0x80 | ((cp >> 6) & 0x3F))); putchar((int)(0x80 | (cp & 0x3F))); }",
            "  else { putchar((int)(0xF0 | (cp >> 18))); putchar((int)(0x80 | ((cp >> 12) & 0x3F))); putchar((int)(0x80 | ((cp >> 6) & 0x3F))); putchar((int)(0x80 | (cp & 0x3F))); }",
            "  putchar('\\n');",
            "}",
            "__attribute__((weak)) void kk_println_any(void* obj) {",
            "  if ((intptr_t)obj == KK_NULL_SENTINEL) { puts(\"null\"); return; }",
            "  if ((intptr_t)obj > -(intptr_t)0x100000000LL && (intptr_t)obj < (intptr_t)0x100000000LL) {",
            "    printf(\"%ld\\n\", (long)(intptr_t)obj);",
            "    return;",
            "  }",
            "  KKBoxedValue* maybeBox = (KKBoxedValue*)(void*)obj;",
            "  if (maybeBox && maybeBox->tag == KK_BOX_TAG_BOOL) {",
            "    puts(maybeBox->value ? \"true\" : \"false\");",
            "    return;",
            "  }",
            "  if (maybeBox && maybeBox->tag == KK_BOX_TAG_INT) {",
            "    printf(\"%ld\\n\", (long)maybeBox->value);",
            "    return;",
            "  }",
            "  if (maybeBox && maybeBox->tag == KK_BOX_TAG_LONG) {",
            "    printf(\"%ld\\n\", (long)maybeBox->value);",
            "    return;",
            "  }",
            "  if (maybeBox && maybeBox->tag == KK_BOX_TAG_FLOAT) {",
            "    kk_println_float(maybeBox->value);",
            "    return;",
            "  }",
            "  if (maybeBox && maybeBox->tag == KK_BOX_TAG_DOUBLE) {",
            "    kk_println_double(maybeBox->value);",
            "    return;",
            "  }",
            "  if (maybeBox && maybeBox->tag == KK_BOX_TAG_CHAR) {",
            "    kk_println_char(maybeBox->value);",
            "    return;",
            "  }",
            "  KKString* s = (KKString*)obj;",
            "  if (!s) { puts(\"null\"); return; }",
            "  if (s->len < 0 || s->len > (1 << 20)) {",
            "    printf(\"%ld\\n\", (long)(intptr_t)obj);",
            "    return;",
            "  }",
            "  if (s->len > 0 && !s->bytes) {",
            "    printf(\"%ld\\n\", (long)(intptr_t)obj);",
            "    return;",
            "  }",
            "  if (s->bytes && s->len > 0) fwrite(s->bytes, 1, (size_t)s->len, stdout);",
            "  fputc('\\n', stdout);",
            "}",
            "typedef struct {",
            "  intptr_t functionId;",
            "  intptr_t label;",
            "  intptr_t completion;",
            "  intptr_t* spills;",
            "  intptr_t spillCount;",
            "} KKContinuationState;",
            "__attribute__((weak)) intptr_t kk_coroutine_suspended(void) {",
            "  static int32_t token = 0;",
            "  return (intptr_t)(void*)&token;",
            "}",
            "__attribute__((weak)) intptr_t kk_coroutine_continuation_new(intptr_t functionId) {",
            "  KKContinuationState* state = (KKContinuationState*)malloc(sizeof(KKContinuationState));",
            "  if (!state) return 0;",
            "  state->functionId = functionId;",
            "  state->label = 0;",
            "  state->completion = 0;",
            "  state->spills = NULL;",
            "  state->spillCount = 0;",
            "  return (intptr_t)state;",
            "}",
            "__attribute__((weak)) intptr_t kk_coroutine_state_enter(intptr_t continuation, intptr_t functionId) {",
            "  KKContinuationState* state = (KKContinuationState*)(void*)continuation;",
            "  if (!state) return 0;",
            "  if (state->functionId != functionId) {",
            "    state->functionId = functionId;",
            "    state->label = 0;",
            "  }",
            "  return state->label;",
            "}",
            "__attribute__((weak)) intptr_t kk_coroutine_state_set_label(intptr_t continuation, intptr_t label) {",
            "  KKContinuationState* state = (KKContinuationState*)(void*)continuation;",
            "  if (!state) return label;",
            "  state->label = label;",
            "  return label;",
            "}",
            "__attribute__((weak)) intptr_t kk_coroutine_state_set_spill(intptr_t continuation, intptr_t slot, intptr_t value) {",
            "  KKContinuationState* state = (KKContinuationState*)(void*)continuation;",
            "  if (!state || slot < 0) return value;",
            "  if (slot >= state->spillCount) {",
            "    intptr_t newCount = slot + 1;",
            "    intptr_t* resized = (intptr_t*)realloc(state->spills, (size_t)newCount * sizeof(intptr_t));",
            "    if (!resized) return value;",
            "    for (intptr_t i = state->spillCount; i < newCount; ++i) resized[i] = 0;",
            "    state->spills = resized;",
            "    state->spillCount = newCount;",
            "  }",
            "  state->spills[slot] = value;",
            "  return value;",
            "}",
            "__attribute__((weak)) intptr_t kk_coroutine_state_get_spill(intptr_t continuation, intptr_t slot) {",
            "  KKContinuationState* state = (KKContinuationState*)(void*)continuation;",
            "  if (!state || slot < 0 || slot >= state->spillCount || !state->spills) return 0;",
            "  return state->spills[slot];",
            "}",
            "__attribute__((weak)) intptr_t kk_coroutine_state_set_completion(intptr_t continuation, intptr_t value) {",
            "  KKContinuationState* state = (KKContinuationState*)(void*)continuation;",
            "  if (!state) return value;",
            "  state->completion = value;",
            "  return value;",
            "}",
            "__attribute__((weak)) intptr_t kk_coroutine_state_get_completion(intptr_t continuation) {",
            "  KKContinuationState* state = (KKContinuationState*)(void*)continuation;",
            "  if (!state) return 0;",
            "  return state->completion;",
            "}",
            "__attribute__((weak)) intptr_t kk_coroutine_state_exit(intptr_t continuation, intptr_t value) {",
            "  KKContinuationState* state = (KKContinuationState*)(void*)continuation;",
            "  if (state) {",
            "    if (state->spills) free(state->spills);",
            "    free(state);",
            "  }",
            "  return value;",
            "}",
            "typedef intptr_t (*KKSuspendEntryFn)(intptr_t continuation, intptr_t* outThrown);",
            "__attribute__((weak)) intptr_t kk_kxmini_delay(intptr_t milliseconds, intptr_t continuation) {",
            "  (void)continuation;",
            "  if (milliseconds > 0) {",
            "    usleep((useconds_t)(milliseconds * 1000));",
            "  }",
            "  return kk_coroutine_suspended();",
            "}",
            "__attribute__((weak)) intptr_t delay(intptr_t milliseconds, intptr_t* outThrown) {",
            "  if (outThrown) { *outThrown = 0; }",
            "  return kk_kxmini_delay(milliseconds, 0);",
            "}",
            "__attribute__((weak)) intptr_t kk_kxmini_run_loop(KKSuspendEntryFn entry, intptr_t functionId) {",
            "  if (!entry) return 0;",
            "  intptr_t continuation = kk_coroutine_continuation_new(functionId);",
            "  intptr_t suspended = kk_coroutine_suspended();",
            "  while (1) {",
            "    intptr_t thrown = 0;",
            "    intptr_t result = entry(continuation, &thrown);",
            "    if (thrown != 0) {",
            "      kk_coroutine_state_exit(continuation, 0);",
            "      return 0;",
            "    }",
            "    if (result != suspended) {",
            "      return result;",
            "    }",
            "  }",
            "}",
            "__attribute__((weak)) intptr_t kk_kxmini_run_blocking(intptr_t entryRaw, intptr_t functionId) {",
            "  KKSuspendEntryFn entry = (KKSuspendEntryFn)(void*)entryRaw;",
            "  return kk_kxmini_run_loop(entry, functionId);",
            "}",
            "__attribute__((weak)) intptr_t kk_kxmini_launch(intptr_t entryRaw, intptr_t functionId) {",
            "  (void)kk_kxmini_run_blocking(entryRaw, functionId);",
            "  return 0;",
            "}",
            "__attribute__((weak)) intptr_t kk_kxmini_async(intptr_t entryRaw, intptr_t functionId) {",
            "  return kk_kxmini_run_blocking(entryRaw, functionId);",
            "}",
            "__attribute__((weak)) intptr_t kk_kxmini_async_await(intptr_t handle) {",
            "  return handle;",
            "}",
            "/* --- Flow stubs (P5-88) --- */",
            "__attribute__((weak)) intptr_t kk_flow_create(intptr_t emitterFnPtr, intptr_t continuation) {",
            "  (void)continuation;",
            "  return emitterFnPtr;",
            "}",
            "__attribute__((weak)) intptr_t kk_flow_emit(intptr_t flowHandle, intptr_t value, intptr_t continuation) {",
            "  (void)flowHandle; (void)continuation;",
            "  return value;",
            "}",
            "__attribute__((weak)) intptr_t kk_flow_collect(intptr_t flowHandle, intptr_t collectorFnPtr, intptr_t continuation) {",
            "  (void)flowHandle; (void)collectorFnPtr; (void)continuation;",
            "  return 0;",
            "}",
            "/* --- Dispatcher stubs (P5-133) --- */",
            "#define KK_DISPATCHER_DEFAULT 0x4B4B4401",
            "#define KK_DISPATCHER_IO      0x4B4B4402",
            "#define KK_DISPATCHER_MAIN    0x4B4B4403",
            "__attribute__((weak)) intptr_t kk_dispatcher_default(void) { return KK_DISPATCHER_DEFAULT; }",
            "__attribute__((weak)) intptr_t kk_dispatcher_io(void)      { return KK_DISPATCHER_IO; }",
            "__attribute__((weak)) intptr_t kk_dispatcher_main(void)    { return KK_DISPATCHER_MAIN; }",
            "__attribute__((weak)) intptr_t kk_with_context(intptr_t dispatcher, intptr_t blockFnPtr, intptr_t continuation) {",
            "  (void)dispatcher;",
            "  KKSuspendEntryFn entry = (KKSuspendEntryFn)(void*)blockFnPtr;",
            "  if (!entry) return 0;",
            "  intptr_t thrown = 0;",
            "  intptr_t result = entry(continuation, &thrown);",
            "  if (thrown != 0) return 0;",
            "  return result;",
            "}",
            "/* --- Channel stubs (P5-134) --- */",
            "typedef struct { intptr_t* buf; intptr_t head; intptr_t tail; intptr_t cap; intptr_t closed; } KKChannel;",
            "__attribute__((weak)) intptr_t kk_channel_create(intptr_t capacity) {",
            "  KKChannel* ch = (KKChannel*)calloc(1, sizeof(KKChannel));",
            "  if (!ch) return 0;",
            "  ch->cap = capacity > 0 ? capacity : 1;",
            "  ch->buf = (intptr_t*)calloc((size_t)ch->cap, sizeof(intptr_t));",
            "  if (!ch->buf) { free(ch); return 0; }",
            "  ch->head = 0; ch->tail = 0; ch->closed = 0;",
            "  return (intptr_t)ch;",
            "}",
            "__attribute__((weak)) intptr_t kk_channel_send(intptr_t handle, intptr_t value, intptr_t continuation) {",
            "  (void)continuation;",
            "  KKChannel* ch = (KKChannel*)(void*)handle;",
            "  if (!ch || ch->closed) return 0;",
            "  if (ch->tail - ch->head >= ch->cap) return 0;",
            "  ch->buf[ch->tail % ch->cap] = value;",
            "  ch->tail++;",
            "  return value;",
            "}",
            "__attribute__((weak)) intptr_t kk_channel_receive(intptr_t handle, intptr_t continuation) {",
            "  (void)continuation;",
            "  KKChannel* ch = (KKChannel*)(void*)handle;",
            "  if (!ch || ch->head >= ch->tail) return 0;",
            "  intptr_t val = ch->buf[ch->head % ch->cap];",
            "  ch->head++;",
            "  return val;",
            "}",
            "__attribute__((weak)) intptr_t kk_channel_close(intptr_t handle) {",
            "  KKChannel* ch = (KKChannel*)(void*)handle;",
            "  if (ch) ch->closed = 1;",
            "  return 0;",
            "}",
            "/* --- awaitAll stub (P5-135) --- */",
            "__attribute__((weak)) intptr_t kk_await_all(intptr_t handlesArray, intptr_t count) {",
            "  (void)handlesArray; (void)count;",
            "  return 0;",
            "}",
            "/* --- Range/progression runtime (P5-68) --- */",
            "typedef struct { intptr_t first; intptr_t last; intptr_t step; } KKRange;",
            "typedef struct { intptr_t current; intptr_t last; intptr_t step; } KKRangeIterator;",
            "__attribute__((weak)) intptr_t kk_op_rangeTo(intptr_t a, intptr_t b) {",
            "  KKRange* r = (KKRange*)malloc(sizeof(KKRange));",
            "  if (!r) return 0;",
            "  r->first = a; r->last = b; r->step = 1;",
            "  return (intptr_t)r;",
            "}",
            "__attribute__((weak)) intptr_t kk_op_rangeUntil(intptr_t a, intptr_t b) {",
            "  KKRange* r = (KKRange*)malloc(sizeof(KKRange));",
            "  if (!r) return 0;",
            "  r->first = a; r->last = b - 1; r->step = 1;",
            "  return (intptr_t)r;",
            "}",
            "__attribute__((weak)) intptr_t kk_op_downTo(intptr_t a, intptr_t b) {",
            "  KKRange* r = (KKRange*)malloc(sizeof(KKRange));",
            "  if (!r) return 0;",
            "  r->first = a; r->last = b; r->step = -1;",
            "  return (intptr_t)r;",
            "}",
            "__attribute__((weak)) intptr_t kk_op_step(intptr_t rangeRaw, intptr_t stepVal) {",
            "  KKRange* r = (KKRange*)(void*)rangeRaw;",
            "  if (!r || stepVal <= 0) return rangeRaw;",
            "  KKRange* nr = (KKRange*)malloc(sizeof(KKRange));",
            "  if (!nr) return rangeRaw;",
            "  nr->first = r->first; nr->last = r->last;",
            "  if (r->step < 0) { nr->step = -stepVal; } else { nr->step = stepVal; }",
            "  return (intptr_t)nr;",
            "}",
            "__attribute__((weak)) intptr_t kk_range_iterator(intptr_t rangeRaw) {",
            "  KKRange* r = (KKRange*)(void*)rangeRaw;",
            "  if (!r) return 0;",
            "  KKRangeIterator* it = (KKRangeIterator*)malloc(sizeof(KKRangeIterator));",
            "  if (!it) return 0;",
            "  it->current = r->first; it->last = r->last; it->step = r->step;",
            "  return (intptr_t)it;",
            "}",
            "__attribute__((weak)) intptr_t kk_range_hasNext(intptr_t iterRaw) {",
            "  KKRangeIterator* it = (KKRangeIterator*)(void*)iterRaw;",
            "  if (!it) return 0;",
            "  if (it->step > 0) return it->current <= it->last ? 1 : 0;",
            "  if (it->step < 0) return it->current >= it->last ? 1 : 0;",
            "  return 0;",
            "}",
            "__attribute__((weak)) intptr_t kk_range_next(intptr_t iterRaw) {",
            "  KKRangeIterator* it = (KKRangeIterator*)(void*)iterRaw;",
            "  if (!it) return 0;",
            "  intptr_t val = it->current;",
            "  it->current += it->step;",
            "  return val;",
            "}",
            "/* vtable/itable dispatch helpers */",
            "typedef intptr_t (*KKVTableEntry)();",
            "__attribute__((weak)) KKVTableEntry kk_vtable_lookup(intptr_t receiver, intptr_t slot) {",
            "  if (!receiver || receiver == KK_NULL_SENTINEL) return (KKVTableEntry)0;",
            "  intptr_t* obj = (intptr_t*)(void*)receiver;",
            "  intptr_t typeInfo = obj[0];",
            "  if (!typeInfo) return (KKVTableEntry)0;",
            "  KKVTableEntry* vtable = (KKVTableEntry*)(void*)typeInfo;",
            "  return vtable[slot];",
            "}",
            "__attribute__((weak)) KKVTableEntry kk_itable_lookup(intptr_t receiver, intptr_t ifaceSlot, intptr_t methodSlot) {",
            "  if (!receiver || receiver == KK_NULL_SENTINEL) return (KKVTableEntry)0;",
            "  intptr_t* obj = (intptr_t*)(void*)receiver;",
            "  intptr_t typeInfo = obj[0];",
            "  if (!typeInfo) return (KKVTableEntry)0;",
            "  intptr_t* typeInfoArr = (intptr_t*)(void*)typeInfo;",
            "  intptr_t itablePtr = typeInfoArr[ifaceSlot];",
            "  if (!itablePtr) return (KKVTableEntry)0;",
            "  KKVTableEntry* itable = (KKVTableEntry*)(void*)itablePtr;",
            "  return itable[methodSlot];",
            "}",
            ""
    ]

    func cRuntimePreamble() -> [String] {
        Self.fixedRuntimePreamble
    }
}
