import Foundation

extension LLVMBackend {
    /// Minimal C declarations sufficient for compiling user code when the full
    /// runtime preamble has already been compiled into a cached stub object.
    /// Includes type definitions, macros, and extern declarations for all
    /// runtime functions that user code may reference.
    ///
    /// Stored as a static constant to avoid re-creating the array on every
    /// compilation (P5-64).
    static let fixedExternDeclarations: [String] = [
        "#define _DEFAULT_SOURCE",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "#include <stdlib.h>",
        "#include <stdio.h>",
        "#include <string.h>",
        "#include <unistd.h>",
        "#include <math.h>",
        "#define KK_NULL_SENTINEL ((intptr_t)INTPTR_MIN)",
        "",
        "/* Type definitions shared with runtime stub */",
        "typedef struct { int32_t len; uint8_t* bytes; } KKString;",
        "typedef struct { uint32_t rootCount; const int32_t* rootOffsets; } KKFrameMapDescriptor;",
        "typedef intptr_t (*KKVTableEntry)();",
        "typedef intptr_t (*KKSuspendEntryFn)(intptr_t continuation, intptr_t* outThrown);",
        "",
        "/* Extern declarations for runtime functions in cached stub */",
        "extern void kk_register_frame_map(uint32_t functionID, const void* mapPtr);",
        "extern void kk_push_frame(uint32_t functionID, void* frameBase);",
        "extern void kk_pop_frame(void);",
        "extern void kk_register_global_root(void** slot);",
        "extern void kk_unregister_global_root(void** slot);",
        "extern void kk_register_coroutine_root(void* value);",
        "extern void kk_unregister_coroutine_root(void* value);",
        "extern void* kk_string_from_utf8(const uint8_t* ptr, int32_t len);",
        "extern void* kk_any_to_string(intptr_t value, int32_t tag);",
        "extern void* kk_string_concat(void* a, void* b);",
        "extern intptr_t kk_string_compareTo(void* a, void* b);",
        "extern intptr_t kk_array_new(intptr_t length);",
        "extern intptr_t kk_array_get(intptr_t arrayRaw, intptr_t index, intptr_t* outThrown);",
        "extern intptr_t kk_array_set(intptr_t arrayRaw, intptr_t index, intptr_t value, intptr_t* outThrown);",
        "extern intptr_t kk_vararg_spread_concat(intptr_t pairsArrayRaw, intptr_t pairCount);",
        "extern intptr_t kk_box_int(intptr_t value);",
        "extern intptr_t kk_box_bool(intptr_t value);",
        "extern intptr_t kk_unbox_int(intptr_t obj);",
        "extern intptr_t kk_unbox_bool(intptr_t obj);",
        "extern intptr_t kk_box_long(intptr_t value);",
        "extern intptr_t kk_unbox_long(intptr_t obj);",
        "extern intptr_t kk_float_to_bits(float f);",
        "extern float kk_bits_to_float(intptr_t v);",
        "extern intptr_t kk_double_to_bits(double d);",
        "extern double kk_bits_to_double(intptr_t v);",
        "extern intptr_t kk_box_float(intptr_t value);",
        "extern intptr_t kk_unbox_float(intptr_t obj);",
        "extern intptr_t kk_box_double(intptr_t value);",
        "extern intptr_t kk_unbox_double(intptr_t obj);",
        "extern intptr_t kk_box_char(intptr_t value);",
        "extern intptr_t kk_unbox_char(intptr_t obj);",
        "extern intptr_t kk_int_to_float_bits(intptr_t v);",
        "extern intptr_t kk_int_to_double_bits(intptr_t v);",
        "extern intptr_t kk_float_to_double_bits(intptr_t v);",
        "extern void kk_println_long(intptr_t v);",
        "extern void kk_println_float(intptr_t v);",
        "extern void kk_println_double(intptr_t v);",
        "extern void kk_println_char(intptr_t v);",
        "extern void kk_println_any(void* obj);",
        "extern intptr_t kk_throwable_is_cancellation(intptr_t throwableRaw);",
        "extern intptr_t kk_coroutine_suspended(void);",
        "extern intptr_t kk_coroutine_continuation_new(intptr_t functionId);",
        "extern intptr_t kk_coroutine_state_enter(intptr_t continuation, intptr_t functionId);",
        "extern intptr_t kk_coroutine_state_set_label(intptr_t continuation, intptr_t label);",
        "extern intptr_t kk_coroutine_state_exit(intptr_t continuation, intptr_t value);",
        "extern intptr_t kk_coroutine_state_set_spill(intptr_t continuation, intptr_t slot, intptr_t value);",
        "extern intptr_t kk_coroutine_state_get_spill(intptr_t continuation, intptr_t slot);",
        "extern intptr_t kk_coroutine_state_set_completion(intptr_t continuation, intptr_t value);",
        "extern intptr_t kk_coroutine_state_get_completion(intptr_t continuation);",
        "extern intptr_t kk_kxmini_delay(intptr_t milliseconds, intptr_t continuation);",
        "extern intptr_t delay(intptr_t milliseconds, intptr_t* outThrown);",
        "extern intptr_t kk_kxmini_run_loop(KKSuspendEntryFn entry, intptr_t functionId);",
        "extern intptr_t kk_kxmini_run_blocking(intptr_t entryRaw, intptr_t functionId);",
        "extern intptr_t kk_kxmini_launch(intptr_t entryRaw, intptr_t functionId);",
        "extern intptr_t kk_kxmini_async(intptr_t entryRaw, intptr_t functionId);",
        "extern intptr_t kk_kxmini_async_await(intptr_t handle);",
        "extern intptr_t kk_flow_create(intptr_t emitterFnPtr, intptr_t continuation);",
        "extern intptr_t kk_flow_emit(intptr_t flowHandle, intptr_t value, intptr_t continuation);",
        "extern intptr_t kk_flow_collect(intptr_t flowHandle, intptr_t collectorFnPtr, intptr_t continuation);",
        "extern intptr_t kk_dispatcher_default(void);",
        "extern intptr_t kk_dispatcher_io(void);",
        "extern intptr_t kk_dispatcher_main(void);",
        "extern intptr_t kk_with_context(intptr_t dispatcher, intptr_t blockFnPtr, intptr_t continuation);",
        "extern intptr_t kk_channel_create(intptr_t capacity);",
        "extern intptr_t kk_channel_send(intptr_t handle, intptr_t value, intptr_t continuation);",
        "extern intptr_t kk_channel_receive(intptr_t handle, intptr_t continuation);",
        "extern intptr_t kk_channel_close(intptr_t handle);",
        "extern intptr_t kk_await_all(intptr_t handlesArray, intptr_t count);",
        "extern KKVTableEntry kk_vtable_lookup(intptr_t receiver, intptr_t slot);",
        "extern KKVTableEntry kk_itable_lookup(intptr_t receiver, intptr_t ifaceSlot, intptr_t methodSlot);",
        "extern intptr_t kk_op_notnull(intptr_t value, intptr_t* outThrown);",
        "extern intptr_t kk_op_elvis(intptr_t lhs, intptr_t rhs);",
        "/* Range/progression runtime (P5-68) */",
        "typedef struct { intptr_t first; intptr_t last; intptr_t step; } KKRange;",
        "typedef struct { intptr_t current; intptr_t last; intptr_t step; } KKRangeIterator;",
        "extern intptr_t kk_op_rangeTo(intptr_t a, intptr_t b);",
        "extern intptr_t kk_op_rangeUntil(intptr_t a, intptr_t b);",
        "extern intptr_t kk_op_downTo(intptr_t a, intptr_t b);",
        "extern intptr_t kk_op_step(intptr_t rangeRaw, intptr_t stepVal);",
        "extern intptr_t kk_range_iterator(intptr_t rangeRaw);",
        "extern intptr_t kk_range_hasNext(intptr_t iterRaw);",
        "extern intptr_t kk_range_next(intptr_t iterRaw);",
        "/* Delegate runtime (P5-80) */",
        "extern intptr_t kk_lazy_create(intptr_t initFnPtr, intptr_t mode);",
        "extern intptr_t kk_lazy_get_value(intptr_t handle);",
        "extern intptr_t kk_observable_create(intptr_t initialValue, intptr_t callbackFnPtr);",
        "extern intptr_t kk_observable_get_value(intptr_t handle);",
        "extern intptr_t kk_observable_set_value(intptr_t handle, intptr_t newValue);",
        "extern intptr_t kk_vetoable_create(intptr_t initialValue, intptr_t callbackFnPtr);",
        "extern intptr_t kk_vetoable_get_value(intptr_t handle);",
        "extern intptr_t kk_vetoable_set_value(intptr_t handle, intptr_t newValue);",
        "/* Bitwise/shift runtime (P5-103) */",
        "extern intptr_t kk_bitwise_and(intptr_t a, intptr_t b);",
        "extern intptr_t kk_bitwise_or(intptr_t a, intptr_t b);",
        "extern intptr_t kk_bitwise_xor(intptr_t a, intptr_t b);",
        "extern intptr_t kk_op_inv(intptr_t a);",
        "extern intptr_t kk_op_shl(intptr_t a, intptr_t b);",
        "extern intptr_t kk_op_shr(intptr_t a, intptr_t b);",
        "extern intptr_t kk_op_ushr(intptr_t a, intptr_t b);",
        "/* Collection literal runtime (P5-84) */",
        "extern intptr_t kk_list_of(intptr_t arrayRaw, intptr_t count);",
        "extern intptr_t kk_list_size(intptr_t listRaw);",
        "extern intptr_t kk_list_get(intptr_t listRaw, intptr_t index);",
        "extern intptr_t kk_list_contains(intptr_t listRaw, intptr_t element);",
        "extern intptr_t kk_list_is_empty(intptr_t listRaw);",
        "extern intptr_t kk_list_iterator(intptr_t listRaw);",
        "extern intptr_t kk_list_iterator_hasNext(intptr_t iterRaw);",
        "extern intptr_t kk_list_iterator_next(intptr_t iterRaw);",
        "extern void* kk_list_to_string(intptr_t listRaw);",
        "extern intptr_t kk_map_of(intptr_t keysArrayRaw, intptr_t valuesArrayRaw, intptr_t count);",
        "extern intptr_t kk_map_size(intptr_t mapRaw);",
        "extern intptr_t kk_map_get(intptr_t mapRaw, intptr_t key);",
        "extern intptr_t kk_map_contains_key(intptr_t mapRaw, intptr_t key);",
        "extern intptr_t kk_map_is_empty(intptr_t mapRaw);",
        "extern void* kk_map_to_string(intptr_t mapRaw);",
        "extern intptr_t kk_map_iterator(intptr_t mapRaw);",
        "extern intptr_t kk_map_iterator_hasNext(intptr_t iterRaw);",
        "extern intptr_t kk_map_iterator_next(intptr_t iterRaw);",
        "extern intptr_t kk_array_of(intptr_t arrayRaw, intptr_t count);",
        "extern intptr_t kk_array_size(intptr_t arrayRaw);",
        ""
    ]
}
