import Foundation

extension LLVMBackend {
    /// Minimal C declarations sufficient for compiling user code when the full
    /// runtime preamble has already been compiled into a cached stub object.
    /// Includes type definitions, macros, and extern declarations for all
    /// runtime functions that user code may reference.
    ///
    /// Stored as a static constant to avoid re-creating the array on every
    /// compilation (P5-64).
    static let fixedExternDeclarations: [String] = [
        "#define _DEFAULT_SOURCE",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "#include <stdlib.h>",
        "#include <stdio.h>",
        "#include <string.h>",
        "#include <unistd.h>",
        "#include <math.h>",
        "#define KK_NULL_SENTINEL ((intptr_t)INTPTR_MIN)",
        "",
        "/* Type definitions shared with runtime stub */",
        "typedef struct { int32_t len; uint8_t* bytes; } KKString;",
        "typedef struct { uint32_t rootCount; const int32_t* rootOffsets; } KKFrameMapDescriptor;",
        "typedef intptr_t (*KKVTableEntry)();",
        "typedef intptr_t (*KKSuspendEntryFn)(intptr_t continuation, intptr_t* outThrown);",
        "",
        "/* Extern declarations for runtime functions in cached stub */",
        "extern void kk_register_frame_map(uint32_t functionID, const void* mapPtr);",
        "extern void kk_push_frame(uint32_t functionID, void* frameBase);",
        "extern void kk_pop_frame(void);",
        "extern void kk_register_global_root(void** slot);",
        "extern void kk_unregister_global_root(void** slot);",
        "extern void kk_register_coroutine_root(void* value);",
        "extern void kk_unregister_coroutine_root(void* value);",
        "extern void* kk_string_from_utf8(const uint8_t* ptr, int32_t len);",
        "extern void* kk_any_to_string(intptr_t value, int32_t tag);",
        "extern void* kk_string_concat(void* a, void* b);",
        "extern intptr_t kk_string_compareTo(void* a, void* b);",
        "extern intptr_t kk_compare_any(intptr_t lhs, intptr_t rhs);",
        "extern intptr_t kk_string_length(intptr_t strRaw);",
        "/* String stdlib (STDLIB-006) */",
        "extern intptr_t kk_string_trim(intptr_t strRaw);",
        "extern intptr_t kk_string_format(intptr_t formatRaw, intptr_t argsArrayRaw);",
        "extern intptr_t kk_string_isNullOrEmpty(intptr_t strRaw);",
        "extern intptr_t kk_string_isNullOrBlank(intptr_t strRaw);",
        "extern intptr_t kk_string_startsWith(intptr_t strRaw, intptr_t prefixRaw);",
        "extern intptr_t kk_string_endsWith(intptr_t strRaw, intptr_t suffixRaw);",
        "extern intptr_t kk_string_contains_str(intptr_t strRaw, intptr_t otherRaw);",
        "extern intptr_t kk_string_replace(intptr_t strRaw, intptr_t oldRaw, intptr_t newRaw);",
        "extern intptr_t kk_string_split(intptr_t strRaw, intptr_t delimRaw);",
        "extern intptr_t kk_string_toInt(intptr_t strRaw, intptr_t* outThrown);",
        "extern intptr_t kk_string_toDouble(intptr_t strRaw, intptr_t* outThrown);",
        "extern intptr_t kk_array_new(intptr_t length);",
        "extern intptr_t kk_object_new(intptr_t length, intptr_t classId);",
        "extern intptr_t kk_object_type_id(intptr_t objectRaw);",
        "extern intptr_t kk_array_get(intptr_t arrayRaw, intptr_t index, intptr_t* outThrown);",
        "extern intptr_t kk_array_set(intptr_t arrayRaw, intptr_t index, intptr_t value, intptr_t* outThrown);",
        "extern intptr_t kk_vararg_spread_concat(intptr_t pairsArrayRaw, intptr_t pairCount);",
        "extern intptr_t kk_type_register_super(intptr_t childTypeId, intptr_t superTypeId);",
        "extern intptr_t kk_type_register_iface(intptr_t childTypeId, intptr_t ifaceTypeId);",
        "extern intptr_t kk_box_int(intptr_t value);",
        "extern intptr_t kk_box_bool(intptr_t value);",
        "extern intptr_t kk_unbox_int(intptr_t obj);",
        "extern intptr_t kk_unbox_bool(intptr_t obj);",
        "extern intptr_t kk_box_long(intptr_t value);",
        "extern intptr_t kk_unbox_long(intptr_t obj);",
        "extern intptr_t kk_float_to_bits(float f);",
        "extern float kk_bits_to_float(intptr_t v);",
        "extern intptr_t kk_double_to_bits(double d);",
        "extern double kk_bits_to_double(intptr_t v);",
        "extern intptr_t kk_box_float(intptr_t value);",
        "extern intptr_t kk_unbox_float(intptr_t obj);",
        "extern intptr_t kk_box_double(intptr_t value);",
        "extern intptr_t kk_unbox_double(intptr_t obj);",
        "extern intptr_t kk_box_char(intptr_t value);",
        "extern intptr_t kk_unbox_char(intptr_t obj);",
        "extern intptr_t kk_int_to_float_bits(intptr_t v);",
        "extern intptr_t kk_int_to_double_bits(intptr_t v);",
        "extern intptr_t kk_float_to_double_bits(intptr_t v);",
        "extern void kk_println_long(intptr_t v);",
        "extern void kk_println_float(intptr_t v);",
        "extern void kk_println_double(intptr_t v);",
        "extern void kk_println_char(intptr_t v);",
        "extern void kk_println_any(void* obj);",
        "extern intptr_t kk_throwable_is_cancellation(intptr_t throwableRaw);",
        "/* CORO-002: Cancellation ABI */",
        "extern intptr_t kk_coroutine_check_cancellation(intptr_t continuation, intptr_t* outThrown);",
        "extern intptr_t kk_is_cancellation_exception(intptr_t throwableRaw);",
        "extern intptr_t kk_job_cancel(intptr_t jobHandle);",
        "extern void kk_coroutine_cancel(intptr_t continuation);",
        "extern intptr_t kk_coroutine_suspended(void);",
        "extern intptr_t kk_coroutine_continuation_new(intptr_t functionId);",
        "extern intptr_t kk_coroutine_state_enter(intptr_t continuation, intptr_t functionId);",
        "extern intptr_t kk_coroutine_state_set_label(intptr_t continuation, intptr_t label);",
        "extern intptr_t kk_coroutine_state_exit(intptr_t continuation, intptr_t value);",
        "extern intptr_t kk_coroutine_state_set_spill(intptr_t continuation, intptr_t slot, intptr_t value);",
        "extern intptr_t kk_coroutine_state_get_spill(intptr_t continuation, intptr_t slot);",
        "extern intptr_t kk_coroutine_state_set_completion(intptr_t continuation, intptr_t value);",
        "extern intptr_t kk_coroutine_state_get_completion(intptr_t continuation);",
        "extern intptr_t kk_kxmini_delay(intptr_t milliseconds, intptr_t continuation);",
        "extern intptr_t delay(intptr_t milliseconds, intptr_t* outThrown);",
        "extern intptr_t kk_kxmini_run_loop(KKSuspendEntryFn entry, intptr_t functionId);",
        "extern intptr_t kk_kxmini_run_blocking(intptr_t entryRaw, intptr_t functionId);",
        "extern intptr_t kk_kxmini_launch(intptr_t entryRaw, intptr_t functionId);",
        "extern intptr_t kk_kxmini_async(intptr_t entryRaw, intptr_t functionId);",
        "extern intptr_t kk_kxmini_async_await(intptr_t handle);",
        "extern intptr_t kk_flow_create(intptr_t emitterFnPtr, intptr_t continuation);",
        "extern intptr_t kk_flow_emit(intptr_t flowHandle, intptr_t value, intptr_t tag);",
        "extern intptr_t kk_flow_collect(intptr_t flowHandle, intptr_t collectorFnPtr, intptr_t continuation);",
        "extern intptr_t kk_flow_retain(intptr_t flowHandle);",
        "extern intptr_t kk_flow_release(intptr_t flowHandle);",
        "extern intptr_t kk_dispatcher_default(void);",
        "extern intptr_t kk_dispatcher_io(void);",
        "extern intptr_t kk_dispatcher_main(void);",
        "extern intptr_t kk_with_context(intptr_t dispatcher, intptr_t blockFnPtr, intptr_t continuation);",
        "extern intptr_t kk_channel_create(intptr_t capacity);",
        "extern intptr_t kk_channel_send(intptr_t handle, intptr_t value, intptr_t continuation);",
        "extern intptr_t kk_channel_receive(intptr_t handle, intptr_t continuation);",
        "extern intptr_t kk_channel_close(intptr_t handle);",
        "extern intptr_t kk_await_all(intptr_t handlesArray, intptr_t count);",
        "extern KKVTableEntry kk_vtable_lookup(intptr_t receiver, intptr_t slot);",
        "extern KKVTableEntry kk_itable_lookup(intptr_t receiver, intptr_t ifaceSlot, intptr_t methodSlot);",
        "extern intptr_t kk_op_notnull(intptr_t value, intptr_t* outThrown);",
        "extern intptr_t kk_op_elvis(intptr_t lhs, intptr_t rhs);",
        "extern intptr_t kk_op_is(intptr_t value, intptr_t typeToken);",
        "extern intptr_t kk_op_cast(intptr_t value, intptr_t typeToken, intptr_t* outThrown);",
        "extern intptr_t kk_op_safe_cast(intptr_t value, intptr_t typeToken);",
        "extern intptr_t kk_op_contains(intptr_t container, intptr_t element);",
        "/* Range/progression runtime (P5-68) */",
        "typedef struct { intptr_t first; intptr_t last; intptr_t step; } KKRange;",
        "typedef struct { intptr_t current; intptr_t last; intptr_t step; } KKRangeIterator;",
        "extern intptr_t kk_op_rangeTo(intptr_t a, intptr_t b);",
        "extern intptr_t kk_op_rangeUntil(intptr_t a, intptr_t b);",
        "extern intptr_t kk_op_downTo(intptr_t a, intptr_t b);",
        "extern intptr_t kk_op_step(intptr_t rangeRaw, intptr_t stepVal);",
        "extern intptr_t kk_range_iterator(intptr_t rangeRaw);",
        "extern intptr_t kk_range_hasNext(intptr_t iterRaw);",
        "extern intptr_t kk_range_next(intptr_t iterRaw);",
        "/* KProperty stub (PROP-007) */",
        "extern intptr_t kk_kproperty_stub_create(intptr_t nameStr, intptr_t returnTypeStr);",
        "extern intptr_t kk_kproperty_stub_name(intptr_t handle);",
        "extern intptr_t kk_kproperty_stub_return_type(intptr_t handle);",
        "/* Delegate runtime (P5-80) */",
        "extern intptr_t kk_lazy_create(intptr_t initFnPtr, intptr_t mode);",
        "extern intptr_t kk_lazy_get_value(intptr_t handle);",
        "extern intptr_t kk_lazy_is_initialized(intptr_t handle);",
        "extern intptr_t kk_observable_create(intptr_t initialValue, intptr_t callbackFnPtr);",
        "extern intptr_t kk_observable_get_value(intptr_t handle);",
        "extern intptr_t kk_observable_set_value(intptr_t handle, intptr_t newValue);",
        "extern intptr_t kk_vetoable_create(intptr_t initialValue, intptr_t callbackFnPtr);",
        "extern intptr_t kk_vetoable_get_value(intptr_t handle);",
        "extern intptr_t kk_vetoable_set_value(intptr_t handle, intptr_t newValue);",
        "/* Bitwise/shift runtime (P5-103) */",
        "extern intptr_t kk_bitwise_and(intptr_t a, intptr_t b);",
        "extern intptr_t kk_bitwise_or(intptr_t a, intptr_t b);",
        "extern intptr_t kk_bitwise_xor(intptr_t a, intptr_t b);",
        "extern intptr_t kk_op_inv(intptr_t a);",
        "extern intptr_t kk_op_shl(intptr_t a, intptr_t b);",
        "extern intptr_t kk_op_shr(intptr_t a, intptr_t b);",
        "extern intptr_t kk_op_ushr(intptr_t a, intptr_t b);",
        "extern void* kk_int_toString_radix(intptr_t value, intptr_t radix);",
        "/* Unsigned conversion (TYPE-005) */",
        "extern intptr_t kk_uint_to_int(intptr_t v);",
        "extern intptr_t kk_ulong_to_int(intptr_t v);",
        "extern intptr_t kk_int_to_uint(intptr_t v);",
        "extern intptr_t kk_long_to_uint(intptr_t v);",
        "extern intptr_t kk_int_to_long(intptr_t v);",
        "extern intptr_t kk_uint_to_long(intptr_t v);",
        "extern intptr_t kk_int_to_ulong(intptr_t v);",
        "extern intptr_t kk_long_to_ulong(intptr_t v);",
        "extern intptr_t kk_uint_to_ulong(intptr_t v);",
        "/* Collection literal runtime (P5-84) */",
        "extern intptr_t kk_list_of(intptr_t arrayRaw, intptr_t count);",
        "extern intptr_t kk_list_size(intptr_t listRaw);",
        "extern intptr_t kk_list_get(intptr_t listRaw, intptr_t index);",
        "extern intptr_t kk_list_contains(intptr_t listRaw, intptr_t element);",
        "extern intptr_t kk_list_is_empty(intptr_t listRaw);",
        "extern intptr_t kk_list_iterator(intptr_t listRaw);",
        "extern intptr_t kk_list_iterator_hasNext(intptr_t iterRaw);",
        "extern intptr_t kk_list_iterator_next(intptr_t iterRaw);",
        "extern intptr_t kk_list_to_string(intptr_t listRaw);",
        "/* Higher-order collection functions (FUNC-003) */",
        "extern intptr_t kk_list_map(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_filter(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_forEach(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_flatMap(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_any(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_none(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_all(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "/* Additional higher-order collection functions (STDLIB-005) */",
        "extern intptr_t kk_list_fold(intptr_t listRaw, intptr_t initial, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_reduce(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_groupBy(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_sortedBy(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_count(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_first(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_last(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_list_find(intptr_t listRaw, intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_map_of(intptr_t keysArrayRaw, intptr_t valuesArrayRaw, intptr_t count);",
        "extern intptr_t kk_map_size(intptr_t mapRaw);",
        "extern intptr_t kk_map_get(intptr_t mapRaw, intptr_t key);",
        "extern intptr_t kk_map_contains_key(intptr_t mapRaw, intptr_t key);",
        "extern intptr_t kk_map_is_empty(intptr_t mapRaw);",
        "extern intptr_t kk_map_to_string(intptr_t mapRaw);",
        "extern intptr_t kk_map_iterator(intptr_t mapRaw);",
        "extern intptr_t kk_map_iterator_hasNext(intptr_t iterRaw);",
        "extern intptr_t kk_map_iterator_next(intptr_t iterRaw);",
        "extern intptr_t kk_array_of(intptr_t arrayRaw, intptr_t count);",
        "extern intptr_t kk_array_size(intptr_t arrayRaw);",
        "/* Pair runtime (FUNC-002) */",
        "extern intptr_t kk_pair_new(intptr_t first, intptr_t second);",
        "extern intptr_t kk_pair_first(intptr_t pairRaw);",
        "extern intptr_t kk_pair_second(intptr_t pairRaw);",
        "extern void* kk_pair_to_string(intptr_t pairRaw);",
        "/* Sequence runtime (STDLIB-003) */",
        "extern intptr_t kk_sequence_from_list(intptr_t listRaw);",
        "extern intptr_t kk_sequence_map(intptr_t seqRaw, intptr_t fnPtr);",
        "extern intptr_t kk_sequence_filter(intptr_t seqRaw, intptr_t fnPtr);",
        "extern intptr_t kk_sequence_take(intptr_t seqRaw, intptr_t count);",
        "extern intptr_t kk_sequence_to_list(intptr_t seqRaw);",
        "extern intptr_t kk_sequence_builder_create(void);",
        "extern intptr_t kk_sequence_builder_yield(intptr_t builderRaw, intptr_t value);",
        "extern intptr_t kk_sequence_builder_build(intptr_t fnPtr);",
        "/* Builder DSL functions (STDLIB-002) */",
        "extern intptr_t kk_build_string(intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_build_list(intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_build_map(intptr_t fnPtr, intptr_t* outThrown);",
        "extern intptr_t kk_string_builder_append(intptr_t strRaw);",
        "extern intptr_t kk_mutable_list_add(intptr_t elem);",
        "extern intptr_t kk_mutable_map_put(intptr_t key, intptr_t value);",
        "",
    ]
}
